version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mini-perplexity:latest
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
